### ISSUE TITLE
ENONET: no such file or directory stat 'c:\users\****\pinokio\api\install_win.Json'

### ISSUE THREAD

**Issue by HowitzerHQ** [kfatehi/LamaCleaner.pinokio#1]
This seems to be a reoccurring issue with multiple scripts, each one, however, is a different missing file

**Comment by kfatehi** [comment]
@HowitzerHQ thank you for that. I am new to pinokio and thought i could just rename it, but i've put it back and will test on linux later to see how to make this package work in both environments.
