### ISSUE TITLE
Error installation Pinokio

### ISSUE THREAD

**Issue by Akossimon** [kfatehi/LamaCleaner.pinokio#3]
Hi,  there is something missing i think, look at my screesnhot 
![Screenshot 2024-05-25 at 13 43 52](https://github.com/kfatehi/IOPaint.pinokio/assets/56002069/771b8da5-2009-4d8f-920f-e6ade9adec2c)

**Comment by ernest88** [comment]
Just create it yourself this doesn't work anymore.

I created a new one as in this comment....
https://github.com/kfatehi/IOPaint.pinokio/issues/2#issuecomment-2076429333

**Comment by kfatehi** [comment]
sorry, unfortunately i don't have the resources to maintain this project, so i will be archiving the repo and removing it from the pinokio package list.
